name: app_maxprotection

description: A new Flutter project.
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  http: ^0.13.1
  url_launcher: ^6.0.3
  equatable: ^2.0.0
  firebase_analytics: ^10.5.1
  firebase_core: ^2.1.4
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.6.3
  fluttertoast: ^8.0.8
  contactus: 1.2.3
  mask_text_input_formatter: ^2.1.0
  local_auth: ^2.1.7
  shared_preferences: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  open_file_safe: ^3.2.3
  path_provider: ^2.0.9
  pdf: ^3.7.3
  just_audio: ^0.9.20
  record_mp3: ^3.0.0
  permission_handler: ^11.0.1
  rxdart: ^0.27.3
  flutter_local_notifications: ^12.0.4
  localstorage: ^4.0.0+1
  flutter_phone_direct_caller: ^2.1.1
  back_button_interceptor: ^7.0.0
  new_version: ^0.3.0
  syncfusion_flutter_charts: ^23.1.41
  dio: ^5.3.3
  speech_to_text: ^6.3.0
  audio_waveforms: ^1.0.4
  file_picker: ^4.5.0
  image_picker: ^1.0.4
  animated_widgets: ^1.1.0


dependency_overrides:
  path_provider_android: 2.0.11
  flutter_layout_grid: 2.0.5
  flutter_math_fork: 0.6.0
  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/logo.webp
    - images/icon.png
    - images/icon2.png
    - images/icon.webp
    - images/Fundo.png
    - images/fundoin.png
    - images/lg.png
    - assets/images/
    - assets/images/ic_share.png
    - assets/alert.mp3
    - assets/bell.mp3
    - images/siem.png
    - images/tkaberto.png
    - images/tkatendimento.png
    - images/zabbix.png
    - images/zabbixinv.png
    - images/message.png
    - images/profilepic.png
    - images/check.png
    - images/controlbg.png
    - images/mic.png
    - images/molde.png
    - images/pdf.png
    - images/bgbutton.png
    - assets/audios/audio1.mp3
    - assets/audios/audio2.mp3
    - assets/audios/audio3.mp3
    - assets/audios/audio4.mp3

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-Black.otf
        - asset: assets/fonts/Metropolis-Light.otf
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-Thin.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  